site_name: Kneron Document Center
#repo_url: http://192.168.200.1:8088/jiyuan/toolchain_manual
#repo_name: GitLab
theme: 'windmill'
nav:
  - Home: index.md
  - Getting Started: getting_start.md
  - Host API Reference: 
    - Host API Intro: host_api_reference.md
    - Application API reference: host_api/app_api.md
    - DME API reference: host_api/dme_api.md
    - System API reference: host_api/system.md
  - Toolchain Docker: 
    - Manual: manual.md
    - End to End Simulator: python_app/app_flow_manual.md 
#theme: 'rtd-dropdown'
