site_name: Document Center
#repo_url: http://192.168.200.1:8088/jiyuan/toolchain_manual
#repo_name: GitLab

theme:
    name: 'windmill'
    custom_dir: 'custom_theme/'

markdown_extensions:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tilde

nav:
  - Kneron AI:                      index.md
  - Kneron PLUS:
    - Getting Started:              plus/getting_started.md
    - Introduction:
      - Introduction:               plus/introduction/introduction.md
      - Install Dependency:         plus/introduction/install_dependency.md
      - Upgrade AI Dongle To KDP2:  plus/introduction/upgrade_ai_device_to_kdp2.md
      - Write Model To Flash:       plus/introduction/write_model_to_flash.md
      - Run Examples:               plus/introduction/run_examples.md
      - Run Examples for Enterprise: plus/introduction/run_examples_enterprise.md
      - Yolo Object Name Mapping:   plus/introduction/yolo_object_name_mapping.md
    - Customized API:
      - Introduction:               plus/customized_api/introduction.md
      - Install Dependency:         plus/customized_api/install_dependency.md
      - Create Single Model Example: plus/customized_api/create_single_model_example.md
      - Create Multiple Models Example: plus/customized_api/create_multiple_models_example.md
      - NCPU Firmware Configuration: plus/customized_api/ncpu_firmware_configuration.md
      - Run Customized Examples:    plus/customized_api/run_customized_examples.md
    - Model Zoo:
      - Introduction:               plus/modelzoo/index.md
      - Classification:             plus/modelzoo/kn-model-zoo_generic_inference_classification.md
      - Object Detection(Fcos):     plus/modelzoo/kn-model-zoo_generic_inference_post_fcos.md
      - Object Detection(Yolo v5):  plus/modelzoo/kn-model-zoo_generic_inference_post_yolov5.md
    - API Reference:
      - v1.2.x:
        - Data Structure:           plus/api_reference_1.2.x/kp_struct.h.md
        - Core API:                 plus/api_reference_1.2.x/kp_core.h.md
        - Inference API:            plus/api_reference_1.2.x/kp_inference.h.md
      - Archive:
        - v1.1.x:
          - Data Structure:         plus/api_reference_1.1.x/kp_struct.h.md
          - Core API:               plus/api_reference_1.1.x/kp_core.h.md
          - Inference API:          plus/api_reference_1.1.x/kp_inference.h.md
        - v1.0.x:
          - Data Structure:         plus/api_reference_1.0.x/kp_struct.h.md
          - Core API:               plus/api_reference_1.0.x/kp_core.h.md
          - Inference API:          plus/api_reference_1.0.x/kp_inference.h.md
  - Firmware SDK:
    - KL520 SDK:
      - v1.6.X:                     520_1.6.0/introduction.md
      - Archive:
        - v1.5.0.0:                 520_1.5.0.0/getting_start.md
        - v1.4.0.0:                 520_1.4.0.0/getting_start.md
        - v1.3.0.0:                 520_1.3.0.0/getting_start.md
    - KL720 SDK:
      - v1.4.X:                     720_1.4.0/introduction.md
      - Archive:
        - v1.3.0:                   720_1.3.0/getting_start_720.md
        - v1.1.0:                   720_1.1.0/getting_start_720.md
    - Archived-Host API Reference:
      - v1.0.0:
        - Host API Reference:       host_lib_1.0.0/kdp_host.h.md
      - v0.9.0:
        - Host API reference:       host_lib_0.9.0/host_api_reference.md
      - v0.8.0:
        - Host API Intro:           host_lib_0.8.0/host_api_reference.md
        - Host API reference:       host_lib_0.8.0/host_api/app_api.md
        - DME API reference:        host_lib_0.8.0/host_api/dme_api.md
        - ISI API reference:        host_lib_0.8.0/host_api/isi_api.md
        - System API reference:     host_lib_0.8.0/host_api/system.md
  - Toolchain Docker:
    - Toolchain Manual: toolchain/manual.md
    - Yolo Example: toolchain/yolo_example.md
    - End to End Simulator: toolchain/python_app/app_flow_manual.md
    - ONNX Converter: toolchain/converters.md
    - Script Tools: toolchain/command_line.md
    - Python API: toolchain/python_api.md
    - Toolchain Common Exceptions: toolchain/errors.md
    - History Versions: toolchain/history.md
  - Model Training:
    - Image Classification: model_training/classification.md
    - Object Detection (fcos): model_training/object_detection_fcos.md
    - Object Detection (YOLOv5): model_training/object_detection_yolov5.md
extra:
    logo: 'imgs/logo.png'
plugins:
  - pdf-export
  - search
