site_name: Document Center
#repo_url: http://192.168.200.1:8088/jiyuan/toolchain_manual
#repo_name: GitLab
theme:
    name: 'windmill'
    custom_dir: 'custom_theme/'
nav:
  - Home: index.md
  - Getting Started:
    - KL520:
      - v1.3.0.0: 520_1.3.0.0/getting_start.md
      - v1.4.0.0: 
        - General: 520_1.4.0.0/getting_start.md
        - Host Kdp2 API(alpha release): 520_1.4.0.0/getting_start_520_kdp2.md
    - KL720: 720/getting_start_720.md
  - Host API Reference:
    - v0.8.0:
      - Host API Intro: host_lib_0.8.0/host_api_reference.md
      - Host API reference: host_lib_0.8.0/host_api/app_api.md
      - DME API reference: host_lib_0.8.0/host_api/dme_api.md
      - ISI API reference: host_lib_0.8.0/host_api/isi_api.md
      - System API reference: host_lib_0.8.0/host_api/system.md
    - v0.9.0:
      - Host API reference: host_lib_0.9.0/host_api_reference.md
      - Host Kdp2 API reference:
        - Data Structure: host_lib_0.9.0/kdp2_api/kdp2_struct.h.md
        - Core API: host_lib_0.9.0/kdp2_api/kdp2_core.h.md
        - APP API: host_lib_0.9.0/kdp2_api/kdp2_app.h.md
        - Post Process API: host_lib_0.9.0/kdp2_api/kdp2_postprocess.h.md
  - Toolchain Docker:
    - Toolchain 520 Manual: toolchain/manual_520.md
    - Toolchain 720 Manual: toolchain/manual_720.md
    - End to End Simulator: toolchain/python_app/app_flow_manual.md
    - ONNX Converter: toolchain/converters.md
extra:
    logo: 'imgs/logo.png'
plugins:
  - pdf-export
